const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94776406272"
const SESSION_ID = "fuQDSDjb#r4gnrYglQRPMgRMhoG2FYyyWUEOv4SDTZIYkB_TwY84"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
